#!/bin/sh

CDROM0="redhat-6.2-i386.iso"
CDROM1="$HOME/Downloads/01-05 WordPerfect 8 for Linux CD_.iso" 

qemu-system-i386 \
    -hda "redhat62-hd.img" \
    -drive file="$CDROM1",index=3,media=cdrom \
    -m 1024 \
    -vga cirrus \
    -nic user,ipv6=off,model=ne2k_pci

    #-drive file="$CDROM0",index=2,media=cdrom \
